name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml
  - pandas=2.1.3
  - pytest=6.2.2
  - numpy=1.22.4
  - scipy=1.13.0
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
